services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6739:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:7.0
    container_name: mongodb-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: maindb
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: